platform :ios, "8.0"

use_frameworks!

target 'RxSwiftValidDemo' do
    pod 'Alamofire', '~> 4.2.0'
    pod 'SnapKit', '~> 3.0.2'
    pod 'HandyJSON', '~> 1.3.0'
    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'Kingfisher', '~> 3.10.1'
    pod 'RxCocoa', '~> 3.5.0'
    pod 'RxSwift', '~> 3.5.0'
end
